spring.datasource.url=jdbc:postgresql://192.168.2.202:5432/furniture_factory
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.security.password.encoding.bcrypt.strength=12
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.number.locale=ru_RU